############################################################
# Dockerfile to build BASIC browser
# Based on Centos
############################################################

# Set the base image to Centos
FROM centos:centos7

# File Author / Maintainer
MAINTAINER Hoang

RUN yum install -y epel-release

RUN yum update -y

RUN yum install -y \ 
	gcc gcc-c++ python2 python2-devel python2-pip python2-virtualenv \
	mercurial git cmake openssl-devel libpng-devel lzo-devel libuuid-devel\
	sqlite-devel zlib-devel bzip2-devel readline-devel \
	gcc-gfortran libgfortran atlas-devel blas-devel lapack-devel \
	httpd mod_wsgi \
	which vim tmux net-tools libtool

#RUN yum install -y boost-devel boost-static

RUN yum clean all

RUN pip install numpy==1.14.2 pandas==0.22.0 cython==0.28.1 certifi==2018.1.18 numexpr==2.6.4 pysam==0.14.1 bx-python==0.8.1 simplejson==3.13.2 anyjson==0.3.3 termcolor==1.1.0 decorator==4.2.1 zipp==1.2.0 configparser==4.0.2 importlib-metadata==1.7.0 PyNaCl==1.1.2 amqp==2.2.2


COPY ./packages/ /BASIC/packages/

RUN (cd /BASIC/packages/fb-pytools/ ; python setup.py install)

# RUN pip install -r /BASIC/packages/python_requirements.txt
RUN pip install asn1crypto==0.24.0 backports.ssl-match-hostname==3.4.0.2 bcrypt==3.1.4 billiard==3.5.0.3 cffi==1.11.5 cryptography==2.2.2 chardet==3.0.4 Django==1.7.8 django-celery==3.2.2 django-extensions==2.0.6 django-tastypie==0.14.1 enum34==1.1.6 Fabric==1.14.0 gunicorn==19.7.1 idna==2.6 iniparse==0.4 ipaddress==1.0.19 kitchen==1.1.1 kombu==4.1.0 mercurial==2.6.2 networkx==2.1 paramiko==2.4.1 pyasn1==0.4.2 pycparser==2.18 pycurl==7.19.0 pygobject==3.22.0 pygpgme==0.3 pyliblzma==0.5.3 pymongo==3.6.1 PyNaCl==1.2.1 python-dateutil==2.7.2 python-lzo==1.11 python-mimeparse==1.6.0 pytz==2018.3 pyxattr==0.5.1 PyYAML==3.12 requests==2.18.4 six==1.11.0 SQLAlchemy==1.2.6 termcolor==1.1.0 typing==3.6.4 urlgrabber==3.10 urllib3==1.22 vine==1.1.4 virtualenv==1.10.1 yum-metadata-parser==1.1.4 bottleneck==1.2.1

